### ISSUE TITLE
Mavlink as dependecy

### ISSUE THREAD

**Issue by guiccbr** [01org/mavlink-vehicles#17]
We're not currently installing the mavlink submodule. This is needed in order to generate the mavlink messages properly. We should either install it in our own cmake or put Mavlink as a dependency on the README.md. I'm inclined to the first option.

**Comment by mbelluzzo** [comment]
If you are going to keep it like a submodule and compile as part of our building process, I think you shouldn't install it. It can mess with the user previous installation (it would do in my machine for example). If it is to be a submodule, keep the usage like ardupilot does (totally internal). If it is to be a dependency like any other library, I do prefer to remove the submodule and add to the dependency list on Readme.md and the user needs to compile/install himself.

**Comment by guiccbr** [comment]
Got your point. I'll keep it as a submodule just like ardupilot, then. I just need to make some changes to make sure the headers are generated with or without a previously installed mavlink.

**Edit: We have decided to remove the submodule and keep mavlink as a dependency instead. PR #20 implements this change.**
