### ISSUE TITLE
Tests are crashing before return

### ISSUE THREAD

**Issue by guiccbr** [01org/mavlink-vehicles#7]
Running the tests as follows results in a core-dump before return.
`build/tests/tests`

This crash is probably being caused by a call to thread.join() in a detached thread. These calls are present in all test procedures, so it must be fixed in all of them.

**Comment by guiccbr** [comment]
Fixed in PR #11

**Comment by rchiossi** [comment]
is there any way to automatically close the issue once the pr is merged?

**Comment by guiccbr** [comment]
@rchiossi, parece que sim. vou testar.

edit: rolou
